### ISSUE TITLE
FindGoblin.cmake typo

### ISSUE THREAD

**Issue by kingadami** [farrer/farso#1]
The line:
`FIND_PATH(GOBLIN_INCLUDE_DIR NAMES goblinconfig.h goblin/goblincofig.h`
should be:
`FIND_PATH(GOBLIN_INCLUDE_DIR NAMES goblinconfig.h goblin/goblinconfig.h`

**Comment by farrer** [comment]
Fixed! Thanks. (and sorry for the long delay)....
