### ISSUE TITLE
Ogre3d Renderer won't compile against ogre3d 2.1 and linux

### ISSUE THREAD

**Issue by kingadami** [farrer/farso#3]
The ogre3d renderer try's to call getSurface() on the surface member which is a pointer of type Surface which does not have that method.  I assume that the same philosophy which was used to address this in the SDL renderer should be used here as well (i.e. casting to OgreSurface* in this case).

**Comment by farrer** [comment]
Merged your changes. Thanks, sorry for the long delay.
